<a href="https://colab.research.google.com/github/YuncheKim/2026_sundaesu/blob/main/sundaesu0921.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world")

Hello world


In [ ]:
x = 3
print("%01d, %02d, %03d, %04d, %05d" %(x,x,x,x,x))
x=256.123
print("실수: %.0f, %.1f, %2f" %(x,x,x))

3, 03, 003, 0003, 00003
실수: 256, 256.1, 256.123000


In [ ]:
x="Hello world"
print("문자열: [%s]" %(x))

문자열: [Hello world]


In [ ]:
contents= ["Regression","Classification", "SVM", "Clustering","Dimention reduction","NN","CNN","AE","GAN","RNN"]
for con in contents:
  if con in["Regression", "Classification","SVM", "Clustering","Dimention reduction"]:
    print ("%s 은(는)기계학습 내용입니다." %con)
  elif con in ["CNN"]:
    print("%s 은(는) convolution neurak network입니다." %con)
  else:
    print("%s 은(는) 심층학습내용입니다." %con)

for (i,con)in enumerate(contents):
  print("[%d/%d]: %s" %(i, len(contents), con))

Regression 은(는)기계학습 내용입니다.
Classification 은(는)기계학습 내용입니다.
SVM 은(는)기계학습 내용입니다.
Clustering 은(는)기계학습 내용입니다.
Dimention reduction 은(는)기계학습 내용입니다.
NN 은(는) 심층학습내용입니다.
CNN 은(는) convolution neurak network입니다.
AE 은(는) 심층학습내용입니다.
GAN 은(는) 심층학습내용입니다.
RNN 은(는) 심층학습내용입니다.
[0/10]: Regression
[1/10]: Classification
[2/10]: SVM
[3/10]: Clustering
[4/10]: Dimention reduction
[5/10]: NN
[6/10]: CNN
[7/10]: AE
[8/10]: GAN
[9/10]: RNN


In [ ]:
def sum(a,b):
  return a+b
x=10.0
y=20.0
print("%.1f + %.1f = %.1f" %(x,y,sum(x,y)))

10.0 + 20.0 = 30.0


In [ ]:
a= []
b = [1,2,3]
c = ["Hello",",","world"]
d = [1,2,3,"x","y","z"]
x = []
print(x)

x.append('a')
print(x)

x.append(123)
print(x)

x.append(["a", "b"])
print(x)

dic = dict()
dic["name"] = "heekyung"
dic["town"] = "Goyangcity"
dic["job"] = "Assistant professor"

print (dic)

[]
['a']
['a', 123]
['a', 123, ['a', 'b']]
{'name': 'heekyung', 'town': 'Goyangcity', 'job': 'Assistant professor'}


In [ ]:
class Student:
  def __init__(self, name):
    self.name = name
  def study(self, hard=False):
    if hard:
      print("%s 학생은 열심히 공부합니다." %self.name)
    else:
      print("%s 학생은 공부합니다." %self.name)

s = Student('김근영')
s.study()
s.study(hard=True)

김근영 학생은 공부합니다.
김근영 학생은 열심히 공부합니다.


In [ ]:
import numpy as np
def print_val(x):
  print ("type", type(x))
  print ("shape", x.shape)
  print ("값:\n", x)
  print (" ")

In [ ]:
x =np.array([1,2,3])
print_val(x)
x[0] = 5
print_val(x)


type <class 'numpy.ndarray'>
shape (3,)
값:
 [1 2 3]
 
type <class 'numpy.ndarray'>
shape (3,)
값:
 [5 2 3]
 


In [ ]:
x =np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

type <class 'numpy.ndarray'>
shape (3,)
값:
 [1 2 3]
 
type <class 'numpy.ndarray'>
shape (3,)
값:
 [5 2 3]
 


In [ ]:
y = np.array([[1,2,3], [4,5,6]])
print_val(y)
a =np.ones((3,2))
print_val(a)
a = np.zeros((2,2))
print_val(a)
a = np.eye(3,3)
print_val(a)



type <class 'numpy.ndarray'>
shape (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 
type <class 'numpy.ndarray'>
shape (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 
type <class 'numpy.ndarray'>
shape (3, 3)
값:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [ ]:
a = np.random.random((4,4))
print_val(a)


type <class 'numpy.ndarray'>
shape (4, 4)
값:
 [[0.68722153 0.30237709 0.41185402 0.8123493 ]
 [0.91147322 0.80038353 0.0560093  0.79112934]
 [0.46358253 0.86463522 0.495632   0.69578895]
 [0.02751411 0.88516602 0.0536751  0.10106149]]
 


In [ ]:
a= np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
print_val(a)
b = a[:2, 1:3]
print_val(b)
row1 = a[1,:]
print_val(row1)


type <class 'numpy.ndarray'>
shape (3, 4)
값:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[2 3]
 [6 7]]
 
type <class 'numpy.ndarray'>
shape (4,)
값:
 [5 6 7 8]
 


In [ ]:
m1 =  np.array([[1,2],[3,4]], dtype=np.float64)
m2 =  np.array([[5,6],[7,8]], dtype=np.float64)
print_val(m1+m2)
print_val(np.add(m1,m2))
print_val(m1 - m2)
print_val(np.subtract(m1,m2))
print_val(m1 * m2)
print_val(np.multiply(m1,m2))
print_val(m1 / m2)
print_val(np.divide(m1,m2))
print_val(np.sqrt(m1))


type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[ 6.  8.]
 [10. 12.]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[ 6.  8.]
 [10. 12.]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[-4. -4.]
 [-4. -4.]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[-4. -4.]
 [-4. -4.]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[ 5. 12.]
 [21. 32.]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[ 5. 12.]
 [21. 32.]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
 


In [ ]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6], [7,8]])
v1 = np.array([[9,10]])
v2 = np.array([[11,12]])
print_val(m1)
print_val(m2)
print_val(v1)
print_val(v2)
print_val(v1.dot(v2.T))
print_val(m1.dot(v1.T))


type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[1 2]
 [3 4]]
 
type <class 'numpy.ndarray'>
shape (2, 2)
값:
 [[5 6]
 [7 8]]
 
type <class 'numpy.ndarray'>
shape (1, 2)
값:
 [[ 9 10]]
 
type <class 'numpy.ndarray'>
shape (1, 2)
값:
 [[11 12]]
 
type <class 'numpy.ndarray'>
shape (1, 1)
값:
 [[219]]
 
type <class 'numpy.ndarray'>
shape (2, 1)
값:
 [[29]
 [67]]
 


In [ ]:
m1 = np.array([[1,2,3], [4,5,6]])
print(m1)
print(m1.shape)
print (np.sum(m1))
print (np.sum(m1, axis=0))
print (np.sum(m1, axis=1))

[[1 2 3]
 [4 5 6]]
(2, 3)
21
[5 7 9]
[ 6 15]
